{% set name = "jupytergis-packages" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/j/jupytergis_core/jupytergis_core-{{ version }}.tar.gz
    sha256: ef53afc7504ff0594a138e07b11bfb86afc4c4502f783b9ebd92313fc8c1a548
    folder: jupytergis_core
  - url: https://pypi.io/packages/source/j/jupytergis_lab/jupytergis_lab-{{ version }}.tar.gz
    sha256: c49433372771cd3fd0b511e85dd564ac119caee64c656ec862f2044333ee6b17
    folder: jupytergis_lab
  - url: https://pypi.io/packages/source/j/jupytergis_qgis/jupytergis_qgis-{{ version }}.tar.gz
    sha256: 33c724b587d12521d748de2350af33e7e7b104e76c63ad80883562516d598df8
    folder: jupytergis_qgis
  - url: https://pypi.io/packages/source/j/jupytergis/jupytergis-{{ version }}.tar.gz
    sha256: 10501e03c2af3b7810905aeab588c32d66e321a9c5fa4e11bceebf553f4c3e96
    folder: jupytergis

build:
  noarch: python
  number: 0


outputs:
  - name: jupytergis_core
    version: {{ version }}
    build:
      noarch: python
      script: |
        cd jupytergis_core
        python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
    requirements:
      host:
        - pip
        - python >=3.8
        - hatchling
        - yarn
        - jupyterlab >=4,<5
        - hatch-jupyter-builder
        - hatch-nodejs-version >=0.3.2
      run:
        - python >=3
        - jupyter_ydoc >=2,<3
        - jupyter-collaboration >=2,<3
        - pycrdt
        - jupyter_server> =2.0.1,<3
        - requests
    test:
      imports:
        - jupytergis_core
      commands:
        - pip check
        - test -f ${PREFIX}/share/jupyter/labextensions/@jupytergis/jupytergis-core/package.json                            # [unix]
        - if not exist %PREFIX%\\share\\jupyter\\labextensions\\@jupytergis/jupytergis-core\\package.json (exit 1)          # [win]
      requires:
        - pip

  - name: jupytergis_lab
    version: {{ version }}
    build:
      noarch: python
      script: |
        cd jupytergis_lab
        python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
    requirements:
      host:
        - pip
        - python >=3.8
        - hatchling
        - yarn
        - jupyterlab >=4,<5
        - hatch-jupyter-builder
        - hatch-nodejs-version >=0.3.2
      run:
        - python >=3.8
        - jupyter_server> =2.0.1,<3
        - jupyter_ydoc >=2,<3
        - jupyter-collaboration >=2,<3
        - ypywidgets >=0.9.0,<0.10
        - yjs-widgets >=0.3.4,<0.4
        - comm >=0.1.2,<0.2
        - pydantic >=2,<3
        - jupytergis_core
        - jupyterlab >=4,<5
        - mapbox-vector-tile
        - requests
      run_constrained:
        - jupytergis_core ={{ version }}
    test:
      imports:
        - jupytergis_lab.notebook.gis_document
      commands:
        - test -f ${PREFIX}/share/jupyter/labextensions/@jupytergis/jupytergis-lab/package.json                            # [unix]
        - if not exist %PREFIX%\\share\\jupyter\\labextensions\\@jupytergis/jupytergis-lab\\package.json (exit 1)          # [win]
      requires:
        - pip

  - name: jupytergis_qgis
    version: {{ version }}
    build:
      noarch: python
      script: |
        cd jupytergis_qgis
        python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
    requirements:
      host:
        - pip
        - python >=3.8
        - hatchling
        - yarn
        - jupyterlab >=4,<5
        - hatch-jupyter-builder
        - hatch-nodejs-version >=0.3.2
      run:
        - python >=3.8
        - jupyter_server >=2.0.1,<3
        - jupytergis_core
        - jupytergis_lab
      run_constrained:
        - jupyterlab >=4,<5
        - jupytergis_lab ={{ version }}
        - jupytergis_core ={{ version }}
    test:
      imports:
        - jupytergis_qgis.qgis_loader
      requires:
        - pip
        - qgis

  - name: jupytergis
    version: {{ version }}
    build:
      noarch: python
      script: |
        cd jupytergis
        python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
    requirements:
      host:
        - pip
        - python >=3.8
        - hatchling
      run:
        - python >=3.8
        - jupytergis_core
        - jupytergis_lab
        - jupytergis_qgis
      run_constrained:
        - jupytergis_core ={{ version }}
        - jupytergis_lab ={{ version }}
        - jupytergis_qgis ={{ version }}
    test:
      imports:
        - jupytergis
      requires:
        - pip

about:
  home: https://github.com/geojupyter/jupytergis
  summary: A JupyterLab extension for collaborative GIS
  description: |
    jupytergis is a JupyterLab extension for GIS with collaborative editing support. It is designed to allow multiple people to work on the same file at the same time, and to facilitate discussion and collaboration around the GIS visualization being created.
    jupytergis has support for QGIS files, which makes it easy to import and export models from QGIS. It also has a range of features for creating and manipulating layers.
  license: BSD-3-Clause
  license_family: BSD
  license_file: jupytergis/LICENSE
  doc_url: https://jupytergis.readthedocs.io/en/latest
  dev_url: https://github.com/geojupyter/jupytergis

extra:
  recipe-maintainers:
    - martinRenou
